/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SecurityPolicyRouteImport } from './routes/security-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services/web-development'
import { Route as ServicesSaasDevelopmentRouteImport } from './routes/services/saas-development'
import { Route as ServicesMobileAppDevelopmentRouteImport } from './routes/services/mobile-app-development'
import { Route as ServicesCustomSoftwareRouteImport } from './routes/services/custom-software'
import { Route as ServicesBusinessAutomationRouteImport } from './routes/services/business-automation'
import { Route as ProductsWholesaleCommerceRouteImport } from './routes/products/wholesale-commerce'
import { Route as ProductsHrmsRouteImport } from './routes/products/hrms'
import { Route as ProductsCrmRouteImport } from './routes/products/crm'
import { Route as ProductsAutoDealerErpRouteImport } from './routes/products/auto-dealer-erp'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityPolicyRoute = SecurityPolicyRouteImport.update({
  id: '/security-policy',
  path: '/security-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/services/web-development',
  path: '/services/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSaasDevelopmentRoute = ServicesSaasDevelopmentRouteImport.update({
  id: '/services/saas-development',
  path: '/services/saas-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileAppDevelopmentRoute =
  ServicesMobileAppDevelopmentRouteImport.update({
    id: '/services/mobile-app-development',
    path: '/services/mobile-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomSoftwareRoute = ServicesCustomSoftwareRouteImport.update({
  id: '/services/custom-software',
  path: '/services/custom-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessAutomationRoute =
  ServicesBusinessAutomationRouteImport.update({
    id: '/services/business-automation',
    path: '/services/business-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsWholesaleCommerceRoute =
  ProductsWholesaleCommerceRouteImport.update({
    id: '/products/wholesale-commerce',
    path: '/products/wholesale-commerce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsHrmsRoute = ProductsHrmsRouteImport.update({
  id: '/products/hrms',
  path: '/products/hrms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCrmRoute = ProductsCrmRouteImport.update({
  id: '/products/crm',
  path: '/products/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAutoDealerErpRoute = ProductsAutoDealerErpRouteImport.update({
  id: '/products/auto-dealer-erp',
  path: '/products/auto-dealer-erp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/founders': typeof FoundersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/security-policy': typeof SecurityPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/products/auto-dealer-erp': typeof ProductsAutoDealerErpRoute
  '/products/crm': typeof ProductsCrmRoute
  '/products/hrms': typeof ProductsHrmsRoute
  '/products/wholesale-commerce': typeof ProductsWholesaleCommerceRoute
  '/services/business-automation': typeof ServicesBusinessAutomationRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/saas-development': typeof ServicesSaasDevelopmentRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/founders': typeof FoundersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/security-policy': typeof SecurityPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/products/auto-dealer-erp': typeof ProductsAutoDealerErpRoute
  '/products/crm': typeof ProductsCrmRoute
  '/products/hrms': typeof ProductsHrmsRoute
  '/products/wholesale-commerce': typeof ProductsWholesaleCommerceRoute
  '/services/business-automation': typeof ServicesBusinessAutomationRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/saas-development': typeof ServicesSaasDevelopmentRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/founders': typeof FoundersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/security-policy': typeof SecurityPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/products/auto-dealer-erp': typeof ProductsAutoDealerErpRoute
  '/products/crm': typeof ProductsCrmRoute
  '/products/hrms': typeof ProductsHrmsRoute
  '/products/wholesale-commerce': typeof ProductsWholesaleCommerceRoute
  '/services/business-automation': typeof ServicesBusinessAutomationRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/saas-development': typeof ServicesSaasDevelopmentRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/founders'
    | '/privacy-policy'
    | '/refund-policy'
    | '/security-policy'
    | '/terms-and-conditions'
    | '/products/auto-dealer-erp'
    | '/products/crm'
    | '/products/hrms'
    | '/products/wholesale-commerce'
    | '/services/business-automation'
    | '/services/custom-software'
    | '/services/mobile-app-development'
    | '/services/saas-development'
    | '/services/web-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/founders'
    | '/privacy-policy'
    | '/refund-policy'
    | '/security-policy'
    | '/terms-and-conditions'
    | '/products/auto-dealer-erp'
    | '/products/crm'
    | '/products/hrms'
    | '/products/wholesale-commerce'
    | '/services/business-automation'
    | '/services/custom-software'
    | '/services/mobile-app-development'
    | '/services/saas-development'
    | '/services/web-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/founders'
    | '/privacy-policy'
    | '/refund-policy'
    | '/security-policy'
    | '/terms-and-conditions'
    | '/products/auto-dealer-erp'
    | '/products/crm'
    | '/products/hrms'
    | '/products/wholesale-commerce'
    | '/services/business-automation'
    | '/services/custom-software'
    | '/services/mobile-app-development'
    | '/services/saas-development'
    | '/services/web-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FoundersRoute: typeof FoundersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SecurityPolicyRoute: typeof SecurityPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ProductsAutoDealerErpRoute: typeof ProductsAutoDealerErpRoute
  ProductsCrmRoute: typeof ProductsCrmRoute
  ProductsHrmsRoute: typeof ProductsHrmsRoute
  ProductsWholesaleCommerceRoute: typeof ProductsWholesaleCommerceRoute
  ServicesBusinessAutomationRoute: typeof ServicesBusinessAutomationRoute
  ServicesCustomSoftwareRoute: typeof ServicesCustomSoftwareRoute
  ServicesMobileAppDevelopmentRoute: typeof ServicesMobileAppDevelopmentRoute
  ServicesSaasDevelopmentRoute: typeof ServicesSaasDevelopmentRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-policy': {
      id: '/security-policy'
      path: '/security-policy'
      fullPath: '/security-policy'
      preLoaderRoute: typeof SecurityPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/services/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/saas-development': {
      id: '/services/saas-development'
      path: '/services/saas-development'
      fullPath: '/services/saas-development'
      preLoaderRoute: typeof ServicesSaasDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-app-development': {
      id: '/services/mobile-app-development'
      path: '/services/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof ServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-software': {
      id: '/services/custom-software'
      path: '/services/custom-software'
      fullPath: '/services/custom-software'
      preLoaderRoute: typeof ServicesCustomSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-automation': {
      id: '/services/business-automation'
      path: '/services/business-automation'
      fullPath: '/services/business-automation'
      preLoaderRoute: typeof ServicesBusinessAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/wholesale-commerce': {
      id: '/products/wholesale-commerce'
      path: '/products/wholesale-commerce'
      fullPath: '/products/wholesale-commerce'
      preLoaderRoute: typeof ProductsWholesaleCommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/hrms': {
      id: '/products/hrms'
      path: '/products/hrms'
      fullPath: '/products/hrms'
      preLoaderRoute: typeof ProductsHrmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/crm': {
      id: '/products/crm'
      path: '/products/crm'
      fullPath: '/products/crm'
      preLoaderRoute: typeof ProductsCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/auto-dealer-erp': {
      id: '/products/auto-dealer-erp'
      path: '/products/auto-dealer-erp'
      fullPath: '/products/auto-dealer-erp'
      preLoaderRoute: typeof ProductsAutoDealerErpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FoundersRoute: FoundersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SecurityPolicyRoute: SecurityPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ProductsAutoDealerErpRoute: ProductsAutoDealerErpRoute,
  ProductsCrmRoute: ProductsCrmRoute,
  ProductsHrmsRoute: ProductsHrmsRoute,
  ProductsWholesaleCommerceRoute: ProductsWholesaleCommerceRoute,
  ServicesBusinessAutomationRoute: ServicesBusinessAutomationRoute,
  ServicesCustomSoftwareRoute: ServicesCustomSoftwareRoute,
  ServicesMobileAppDevelopmentRoute: ServicesMobileAppDevelopmentRoute,
  ServicesSaasDevelopmentRoute: ServicesSaasDevelopmentRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
